# Generated by Django 5.2.4 on 2025-08-03 10:00

from django.db import migrations

def create_profiles_for_existing_users(apps, schema_editor):
    """
    Create profiles for all existing users to ensure data consistency
    before changing the foreign key relationship in blog.Post model.
    """
    User = apps.get_model('accounts', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    
    # Get all existing users
    users = User.objects.all()
    
    # Create a profile for each user if one doesn't already exist
    for user in users:
        # Check if profile already exists
        profile_exists = Profile.objects.filter(user_id=user.id).exists()
        if not profile_exists:
            Profile.objects.create(
                user_id=user.id,
                first_name=user.email.split('@')[0],  # Use email prefix as first name
                last_name='',  # Empty last name
                description=f'Profile for user {user.email}'
            )

def reverse_create_profiles_for_existing_users(apps, schema_editor):
    """
    Reverse operation - delete all profiles created for existing users.
    """
    User = apps.get_model('accounts', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    
    # Delete profiles for existing users
    users = User.objects.all()
    for user in users:
        Profile.objects.filter(user_id=user.id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(
            create_profiles_for_existing_users,
            reverse_create_profiles_for_existing_users
        ),
    ]
